# Generated by Django 4.1.3 on 2022-11-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('0', 'Factory'), ('1', 'Distributor'), ('2', 'Dealership'), ('3', 'Large Retail Chain'), ('4', 'Individual Entrepreneur')], default='0', max_length=2),
        ),
    ]
