# Generated by Django 4.1.3 on 2022-11-11 16:03

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_unit_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='debt',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='unit',
            name='debt_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
